/* eslint-disable global-require */
export default {
  alertCircle: require('./icons/alert-circle.png'),
  iosBack: require('./icons/ios_back.png'),
  arrowLeft: require('./icons/arrow_left.png'),
  arrowRight: require('./icons/arrow_right.png'),
  arrowUp: require('./icons/arrow-up.png'),
  user: require('./icons/user.png'),
  greenTick: require('./icons/green-tick.png'),
  blueUser: require('./icons/blue-user.png'),
  mail: require('./icons/mail.png'),
  transaction: require('./icons/transaction.png'),
  transactions: require('./icons/transactions.png'),
  mapPin: require('./icons/ic_map_pin.png'),
  mapPin2: require('./icons/map-pin.png'),
  orangeTrash: require('./icons/orange-trash.png'),
  deleteAction: require('./icons/delete-action.png'),
  alertCircle2: require('./icons/ic_alert-circle.png'),
  charge: require('./icons/ic_charge.png'),
  chargeWithCode: require('./icons/charge_with_code.png'),
  chargeWithCodeTab: require('./icons/charge_with_code_tab.png'),
  checkCircle: require('./icons/check-circle.png'),
  briefCase: require('./icons/briefcase.png'),
  chevronUp: require('./icons/chevron-up.png'),
  greenCheckmark: require('./icons/green_checkmark.png'),
  circle: require('./icons/cicle.png'),
  greenUser: require('./icons/green-user.png'),
  bluePencil: require('./icons/blue-pencil.png'),
  creditCard: require('./icons/credit-card.png'),
  close: require('./icons/close.png'),
  filterType: require('./icons/ic_filterType.png'),
  back: require('./icons/Back.png'),
  zap: require('./icons/zap.png'),
  cornerUpLeft: require('./icons/corner-up-left.png'),
  cornerUpRight: require('./icons/corner-up-right.png'),
  phone: require('./icons/phone.png'),
  chervonRight: require('./icons/chevron-right.png'),
  delete: require('./icons/Delete.png'),
  frame: require('./icons/Frame.png'),
  favorite: require('./icons/ic_favorite.png'),
  iconSearch: require('./icons/icon-search.png'),
  chargerWithGradient: require('./icons/charger_with_gradient.png'),
  menu: require('./icons/ic_menu.png'),
  filledHart: require('./icons/filled_hart.png'),
  location: require('./icons/location.png'),
  bookOpen: require('./icons/book-open.png'),
  messageSquare: require('./icons/message-square.png'),
  settings: require('./icons/settings.png'),
  facebook: require('./icons/facebook.png'),
  internet: require('./icons/internet.png'),
  'Combo 2': require('./icons/combo2Connector.png'),
  CHAdeMO: require('./icons/chademoConnector.png'),
  'Type 2': require('./icons/type2Connector.png'),
  checkmark: require('./icons/checkmark.png'),
  addCarInput: require('./icons/addCarInput.png'),
  caretDown: require('./icons/caret-down.png'),
  logo: require('./logo.png'),
  defaultCharger: require('./backgrounds/default-charger.png'),
  password: require('./icons/password.png'),
  addCar: require('./icons/add-car.png'),
  mapMode: require('./icons/map-mode.png'),
  remove: require('./icons/remove.png'),
  payment: require('./icons/payment.png'),
}

export const Avatars = [
  require('./avatars/avatar1.png'),
  require('./avatars/avatar2.png'),
  require('./avatars/avatar3.png'),
  require('./avatars/avatar4.png'),
  require('./avatars/avatar5.png'),
  require('./avatars/avatar6.png'),
]

export const Pins = {
  fastPrivateCharging: require('./pins/strokeless/fast-private-charging.png'),
  fastPrivateFree: require('./pins/strokeless/fast-private-free.png'),
  fastPrivateNotWorking: require('./pins/strokeless/fast-private-not-working.png'),
  fastPrivate: require('./pins/strokeless/fast-private.png'),

  fastPublicCharging: require('./pins/strokeless/fast-public-charging.png'),
  fastPublicFree: require('./pins/strokeless/fast-public-free.png'),
  fastPublicNotWorking: require('./pins/strokeless/fast-public-not-working.png'),
  fastPublic: require('./pins/strokeless/fast-public.png'),

  lvl2PrivateCharging: require('./pins/strokeless/lvl2-private-charging.png'),
  lvl2PrivateFree: require('./pins/strokeless/lvl2-private-free.png'),
  lvl2PrivateNotWorking: require('./pins/strokeless/lvl2-private-not-working.png'),
  lvl2Private: require('./pins/strokeless/lvl2-private.png'),

  lvl2PublicCharging: require('./pins/strokeless/lvl2-public-charging.png'),
  lvl2PublicFree: require('./pins/strokeless/lvl2-public-free.png'),
  lvl2PublicNotWorking: require('./pins/strokeless/lvl2-public-not-working.png'),
  lvl2Public: require('./pins/strokeless/lvl2-public.png'),
}

export const StrokedPins = {
  fastPrivateCharging: require('./pins/stroked/fast-private-charging.png'),
  fastPrivateFree: require('./pins/stroked/fast-private-free.png'),
  fastPrivateNotWorking: require('./pins/stroked/fast-private-not-working.png'),
  fastPrivate: require('./pins/stroked/fast-private.png'),

  fastPublicCharging: require('./pins/stroked/fast-public-charging.png'),
  fastPublicFree: require('./pins/stroked/fast-public-free.png'),
  fastPublicNotWorking: require('./pins/stroked/fast-public-not-working.png'),
  fastPublic: require('./pins/stroked/fast-public.png'),

  lvl2PrivateCharging: require('./pins/stroked/lvl2-private-charging.png'),
  lvl2PrivateFree: require('./pins/stroked/lvl2-private-free.png'),
  lvl2PrivateNotWorking: require('./pins/stroked/lvl2-private-not-working.png'),
  lvl2Private: require('./pins/stroked/lvl2-private.png'),

  lvl2PublicCharging: require('./pins/stroked/lvl2-public-charging.png'),
  lvl2PublicFree: require('./pins/stroked/lvl2-public-free.png'),
  lvl2PublicNotWorking: require('./pins/stroked/lvl2-public-not-working.png'),
  lvl2Public: require('./pins/stroked/lvl2-public.png'),
}

export const BoldlyStrokedPins = {
  fastPrivateCharging: require('./pins/boldly-stroked/fast-private-charging.png'),
  fastPrivateFree: require('./pins/boldly-stroked/fast-private-free.png'),
  fastPrivateNotWorking: require('./pins/boldly-stroked/fast-private-not-working.png'),
  fastPrivate: require('./pins/boldly-stroked/fast-private.png'),

  fastPublicCharging: require('./pins/boldly-stroked/fast-public-charging.png'),
  fastPublicFree: require('./pins/boldly-stroked/fast-public-free.png'),
  fastPublicNotWorking: require('./pins/boldly-stroked/fast-public-not-working.png'),
  fastPublic: require('./pins/boldly-stroked/fast-public.png'),

  lvl2PrivateCharging: require('./pins/boldly-stroked/lvl2-private-charging.png'),
  lvl2PrivateFree: require('./pins/boldly-stroked/lvl2-private-free.png'),
  lvl2PrivateNotWorking: require('./pins/boldly-stroked/lvl2-private-not-working.png'),
  lvl2Private: require('./pins/boldly-stroked/lvl2-private.png'),

  lvl2PublicCharging: require('./pins/boldly-stroked/lvl2-public-charging.png'),
  lvl2PublicFree: require('./pins/boldly-stroked/lvl2-public-free.png'),
  lvl2PublicNotWorking: require('./pins/boldly-stroked/lvl2-public-not-working.png'),
  lvl2Public: require('./pins/boldly-stroked/lvl2-public.png'),
}
