import privacyPolicy from './privacyPolicyEn';

export default {
  translation: {
    hello: 'Hello',
    notFound: 'Not found',
    back: 'Back',
    enter: 'Login',
    next: 'Next',
    save: 'Save',
    gel: 'Gel',
    turnOn: 'Turn On',
    km: 'km',
    kwh: 'kw/h',
    kw: 'kw',
    from: '-from',
    till: '-till',
    yes: 'Yes',
    no: 'No',
    done: 'Done',
    minute: 'mins',
    loading: 'Loading ...',
    cancel: 'Cancel',
    update: 'Update',
    pleaseFillInput: 'Please fill input',
    needLocation: 'Need access to location service',
    locationIsDenied: 'Access on location is denied',
    navigateToSettings: 'Navigate to settings',
    chargerString: 'Charger',
    IAgree: 'I Agree',
    welcome: 'Welcome!',
    phoneCodes: 'Phone codes',
    authentication: {
      authentication: 'Authentication',
      number: 'Number',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      newRegistration: 'Register',
      forgotPasswordPage: {
        recoverPassword: 'Recover password',
        smsCode: 'Sms Code',
        receiveCode: 'Receive code',
        newPassword: 'New password',
        repeatPassword: 'Repeat password',
        codeValidity: 'Code is valid during 3 minutes',
      },
      registration: {
        registration: 'Registration',
        name: 'Name',
        surname: 'Surname',
        email: 'Email',
        password: 'Password',
        repeatPassword: 'Repeat password',
        skip: '  Skip',
        success: 'You are registered successfully! You can now charge your car!',
      },
    },
    home: {
      allChargers: 'All chargers',
      authorization: 'Authorization',
      location: 'location',
      locationRequestTextOnDenied: 'Please enable location service',
      organization: 'Organization',
    },

    drawer: {
      tariff: 'Tariff',
      contact: 'Contact',
      faq: 'FAQ',
      partners: 'Partners',
      termsAndConditions: 'Terms and Conditions',
      settings: 'Settings',
      transactions: 'Transactions',
      notifications: 'Notifications',
      logOut: 'Log out',
      changeAvatar: 'Change avatar',
    },

    settings: {
      settings: 'Settings',
      firstname: 'Firstname',
      lastname: 'Lastname',
      mail: 'E-mail',
      phone: 'Phone',
      cards: 'Cards',
      password: 'Password',

      confirmed: 'Confirmed',
      notconfirmed: 'Not Confirmed',
      notAdded: 'Has Not Added',
      add: 'Add',

      editFirstname: 'Edit First Name',
      newFirstname: 'New First Name',

      editLasttname: 'Edit Last Name',
      newLastName: 'New Last Name',

      editPhoneNumber: 'Edit Phone Number',
      phoneNumber: 'Number',

      editMail: 'Edit E-Mail',
      newMail: 'New E-Mail',

      editPassword: 'Edit Password',
      currentPassword: 'Current Password',

      newPassword: 'New Password',
      repeatPassword: 'Repeat Password',

      editCard: 'Payment Method',
      addCard: 'Add Card',

      mapColor: 'Map style',
      automatic: 'Auto',
      mapColorLight: 'Light',
      mapColorDark: 'Dark',
      chooseMapMode: 'Choose map mode',

      addCar: 'Add car',
      manufacturer: 'Manufacturer',
      model: 'Model',
    },
    popup: {
      legend: 'Legend',
      fastNonCommercial: 'Fast non-commercial',
      fastCommercial: 'Fast commercial',
      lvl2NonCommercial: 'Lvl 2 non-commercial',
      lvl2Commercial: 'Lvl 2 commercial',
      busy: 'Busy',
      notWorking: 'Out of order',
      free: 'Free',
      thankYou: 'Thank you',
      automobileChargingFinished: 'Automobile charging finished',
      chargingFinishedWarning: 'Charging finished',
      chargeOff: 'Charge off',
      returned: 'Returned',
      continueCharging: 'Continue charging',
      finishedChargingOfAutomobile: 'Finished charging of automobile',
      warningTextBeforeFine:
        'If you do not plug off the charger you will be fined',
      yourChargingOnFineStarted: 'The fine counting started',
      bankrupt: 'Not enough money',
      paymentFailed: 'Payment failed',
      processFailed: 'Process failed',
    },
    charger: {
      chargeWitchCode: 'Charge witch code',
      enterCode: 'Enter code',
      turnOn: 'Turn on',
      allChargerList: 'All charger list',
      lastUsed: 'Recently used',
    },
    chargerDetail: {
      seeOnMap: 'Show on map',
      kw: 'Kilowatts',
      tariffs: 'Tariffs',
      currentPrices: 'Current prices',
      minutesPrice: '15 minutes price',
      connectors: 'Connectors',
      additionalServices: 'Additional services',
      powerOfChargerType: 'power {{power}}kw/h',
      code: 'code: #{{code}}',
      pleaseAddCardFirst: 'Please add card first',
      maxAllowedCarCharing: 'Max allowed only two car',
      selectConnector: 'Please, select connector',
      chargerIsBusy: 'Charger is occupied',
      minutes: 'Minutes',
    },
    notAuthorized: {
      notAuthorizedText: 'Registration required',
    },
    chooseChargeMethod: {
      choose: 'Choose',
      chooseChargeMethod: 'Choose charging method',
      or: 'Or',
      untilTurnOff: 'Until full charge',
      withEnteringPrice: 'Specify the amount',
    },
    charging: {
      charge: 'Charge',
      chargeAnotherCar: 'Charge another car',
      finish: 'Finish',
    },
    chooseCard: {
      chooseCard: 'Choose card',
      enterPrice: 'Enter amount',
      chargingUntilPlugOff: 'Charging until plug off',
    },
    favourites: {
      favourites: 'Favorites',
    },
    faq: {
      faq: 'FAQ',
      frequentlyAskedQuestions: 'Frequently Asked Questions',
    },
    tariffs: {
      tariffs: 'Tariffs',
      company: 'Company',
      power: 'Power',
      chargerType: 'Charger Type',
    },
    contact: {
      contact: 'Contact',
      address: 'Address',
      phone: 'Phone',
      eMail: 'E-Mail',
      facebookPage: 'Facebook Page',
      webPage: 'Web Page',
      message: 'Message',
      send: ' Send',
      yourFeedbackReceived: 'Your feedback received',
    },
    notifications: {
      notifications: 'Notifications',
    },
    transactions: {
      transactions: 'Transactions',
      details: 'Details',
      duration: 'Duration',
      power: 'Power',
      energy: 'Energy',
      address: 'Address',
      cardNumber: 'Card Number',
      penaltyFee: 'Penalty Fee',
    },
    dropDownAlert: {
      error: 'Error',
      generalError: 'Error encountered',
      generalSuccess: 'Order completed successfully',
      warning: 'Something went wrong',
      pleaseAllowLocation:
        'Please allow access to device location to make route',
      fillCode: 'Please, enter charger code',
      fillAmount: 'Please, enter price amount',
      chargerNotExist: "this kind of charger don't exist",
      successOnFavoriteAdd: 'Charger added Successfully',
      successOnFavoriteRemove: 'Charger deleted successfully',
      informationUpdatedSuccessfully: 'Information updated successfully',
      avatarUpdatedSuccessfully: 'Avatar updated successfully',
      thisUserIsBlocked: 'This user is blocked',
      areYouSureYouWantToLogOut: 'Are you sure you want to log out?',
      needInternetConnection: 'Internet connection required',
      connectionProblem: 'Delay in Connection with charger, please wait',
      pleaseSeeIfChargerIsConnected:
        'Please check if cable is connected properly',
      registration: {
        fillPhoneNumber: 'Please, fill phone number',
        fillName: 'Please, fill name',
        fillSurname: 'Please, fill surname',
        incorrectEmail: 'Email is not valid',
        codeSentSuccessfully: 'SMS Code sent successfully',
        codeLengthError: 'SMS code should be exactly 4 digits long',
        incorrectCode: 'code is incorrect',
        emailAlreadyToken: 'The email has already been taken',
        phoneAlreadyToken: 'The phone number has already been taken.',
        passwordNotEqual: "Passwords don't match",
        needsCardAddOrPleaseSkip: 'Card required, or skip',
        alreadyExists: 'User with this number already exists!',
      },
      editFirstname: {
        firstNameNotEmpty: 'Please, Fill the First Name Field',
        minSize: 'First Name should be at least 3 characters long',
        firstNameChangeSuccess: 'First Name Changed Successfully!',
      },
      editLastname: {
        lastNameNotEmpty: 'Please, Fill the Last Name Field',
        minSize: 'Last Name should be at least 3 characters long',
        lastNameChangeSuccess: 'Last Name Changed Successfully!',
      },
      editEmail: {
        incorrectFormat: 'Email Format is Incorrect',
        editedSuccessfully: 'Email Edited Successfully',
      },
      editPhoneNumber: {
        success: 'Phone Number Edited Successfully',
        phoneTaken: 'Phone Number Already Taken',
      },
      editPassword: {
        success: 'Password Edited Successfully',
        fillCurrentPassword: 'Please, Fill Current Password Field',
        fillRepeatPassword: 'Please, Fill Repeat Password Filed',
        fillNewPassword: 'Please, Fill New Password Field',
        minSize: 'Password Should Contain At Least 8 Characters',
        passwordsMismatch: "Passwords don't identical",
        passwordNotValid: 'Current Password is Not Correct',
      },
      auth: {
        phoneNumberLength: 'The phone number should be exactly 9 digits long.',
        passwordNotEmpty: 'The password field should not be empty',
        userNotFound: 'User not found',
      },
      forgotPassword: {
        smsCodeLength: 'SMS code should be exactly 4 digits long',
        getVerificationCode: 'Get verification code',
        userNotFound: "A user with this phone number isn't found",
        smsCodeExpired: 'SMS code expired',
        fillCode: 'Please, fill the code field',
        newPasswordNotFilled: 'Please, fill the New Password field',
        repeatNewPasswordNotFilled: 'Please fill the Repeat New Password field',
        newPasswordIncorrectLength:
          'New password should contain at least 8 symbols',
        passwordChangedSuccessfully: 'Password changed successfully',
        passwordsNotFilled: 'Please, fill passwords fields',
        verificationCodeIsIncorrect: 'Verification code is incorrect',
        doesNotExist: 'Such user does not exists!',
      },
      contact: {
        Address: 'Something went wrong while opening map...',
        Facebook: 'Something went wrong while opening facebook...',
        Mail: 'Something went wrong while opening mail...',
        Phone: 'Something went wrong while calling...',
        Web: 'Something went wrong while opening website...',
      },
      charging: {
        areUSore: 'Are you sure you want to finish?',
        needToLogIn: 'You need to log in ',
        noRouteFound: 'No route found',
      },
      home: {
        noRouteFound: 'No route found',
      },
      addCar: {
        firstManufacturer: 'Please, select manufacturer...',
        uSureToDelete: 'Are you sure to remove car?',
        youCanAddCar: 'Currently, you have no cars, would you like to add one?',
      },
    },
    addCar: {
      addedCars: 'Added Cars',
      youHaveNoCars: 'You have no cars added...',
    },
    creditCards: {
      uSureToDelete: 'Are you sure, you want to delete your credit card?',
    },
    partners: {
      partnersOrganizations: 'Partner Organizations',
    },
    filterTypes: {
      free: 'Free',
      inUse: 'Occupied',
      fast: 'Fast',
      lvl2: 'Lvl2',
      public: 'Public',
      notPublic: 'Non-Public',
    },
    privacyPolicy,
  },
};
