export default {
  translation: {
    hello: 'Hello',
    notFound: 'Not found',
    back: 'Back',
    enter: 'Login',
    next: 'Next',
    save: 'Save',
    gel: 'Gel',
    turnOn: 'Turn On',
    km: 'km',
    kwh: 'kw/h',
    from: '-from',
    till: '-till',
    yes: 'Yes',
    no: 'No',
    minute: 'mins',
    loading: 'Loading ...',
    cancel: 'Cancel',
    pleaseFillInput: 'Please fill input',
    needLocation: 'Need access to location service',
    locationIsDenied: 'Access on location is denied',
    navigateToSettings: 'Navigate to settings',
    chargerString: 'Charger',
    authentication: {
      authentication: 'Authentication',
      number: 'Number',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      newRegistration: 'Register',
      forgotPasswordPage: {
        recoverPassword: 'Recover password',
        smsCode: 'Sms Code',
        receiveCode: 'Receive code',
        newPassword: 'New password',
        repeatPassword: 'Repeat password',
        codeValidity: 'Code is valid during 3 minutes',
      },
      registration: {
        registration: 'Registration',
        name: 'Name',
        surname: 'Surname',
        email: 'Email',
        password: 'Password',
        repeatPassword: 'Repeat password',
        skip: '  Skip',
      },
    },
    home: {
      allChargers: 'All chargers',
      authorization: 'Authorization',
      location: 'location',
      locationRequestTextOnDenied: 'Please enable location',
      organization: 'Organization',
    },

    drawer: {
      tariff: 'Tariff',
      contact: 'Contact',
      faq: 'FAQ',
      partners: 'Partners',
      termsAndConditions: 'Terms and Conditions',
      settings: 'Settings',
      transactions: 'Transactions',
      notifications: 'Notifications',
      logOut: 'Log out',
      changeAvatar: 'Change avatar',
    },

    settings: {
      settings: 'Settings',
      firstname: 'Firstname',
      lastname: 'Lastname',
      mail: 'E-mail',
      phone: 'Phone',
      cards: 'Cards',
      password: 'Password',

      confirmed: 'Confirmed',
      notconfirmed: 'Not Confirmed',
      notAdded: 'Has Not Added',
      add: 'Add',

      editFirstname: 'Edit First Name',
      newFirstname: 'New First Name',

      editLasttname: 'Edit Last Name',
      newLastName: 'New Last Name',

      editPhoneNumber: 'Edit Phone Number',
      phoneNumber: 'Number',

      editMail: 'Edit E-Mail',
      newMail: 'New E-Mail',

      editPassword: 'Edit Password',
      currentPassword: 'Current Password',

      newPassword: 'New Password',
      repeatPassword: 'Repeat Password',

      editCard: 'Payment Method',
      addCard: 'Add Card',

      mapColor: 'Map color',
      automatic: 'Auto',
      mapColorLight: 'Light',
      mapColorDark: 'Dark',
      chooseMapMode: 'Choose map mode',

      addCar: 'Add car',
      manufacturer: 'Manufacturer',
      model: 'Model',
    },
    popup: {
      legend: 'Legend',
      fastNonCommercial: 'Fast non commercial',
      fastCommercial: 'Fast non commercial',
      lvl2NonCommercial: 'Lvl 2 non commercial',
      lvl2Commercial: 'Lvl 2  commercial',
      busy: 'Busy',
      notWorking: 'Not working',
      free: 'Free',
      thankYou: 'Thank you',
      automobileChargingFinished: 'Automobile charging finished',
      chargingFinishedWarning: ' turn off god damn charger',
      chargeOff: 'Charge off',
      returned: 'Returned',
      continueCharging: 'Continue charging',
      finishedChargingOfAutomobile: 'Finished charging of automobile',
      warningTextBeforeFine:
        'If you do not plug off the charger you will be fined',
      yourChargingOnFineStarted: 'Your charging on fine started',
    },
    charger: {
      chargeWitchCode: 'Charge witch code',
      enterCode: 'Enter code',
      turnOn: 'Turn on',
      allChargerList: 'All charger list',
      lastUsed: 'Last used',
    },
    chargerDetail: {
      seeOnMap: 'See on map',
      currentPrices: 'Current prices',
      minutesPrice: '15 minutes price',
      connectors: 'Connectors',
      additionalServices: 'Additional services',
      powerOfChargerType: 'power {{power}}kw/s',
      code: 'code:#{{code}}',
      pleaseAddCardFirst: 'Please add card first',
      maxAllowedCarCharing: 'Max allowed only two car',
      selectConnector: 'Please, select connector',
    },
    notAuthorized: {
      notAuthorizedText: 'If u want to charge a car u have to register',
    },
    chooseChargeMethod: {
      choose: 'Choose',
      chooseChargeMethod: 'Choose your charging method',
      or: 'Or',
      untilTurnOff: 'until turn off',
      withEnteringPrice: 'With entering price',
    },
    charging: {
      charge: 'Charge',
      chargeAnotherCar: 'Charge other car',
      finish: 'Finish',
    },
    chooseCard: {
      chooseCard: 'Choose card',
      enterPrice: 'Enter price',
      chargingUntilPlugOff: 'Charging until plug off',
    },
    favourites: {
      favourites: 'Favourites',
    },
    faq: {
      faq: 'FAQ',
      frequentlyAskedQuestions: 'Frequently Asked Questions',
    },
    tariffs: {
      tariffs: 'Tariffs',
      company: 'Company',
      power: 'Power',
      chargerType: 'Charger Type',
    },
    contact: {
      contact: 'Contact',
      address: 'Address',
      phone: 'Phone',
      eMail: 'E-Mail',
      facebookPage: 'Facebook Page',
      webPage: 'Web Page',
      message: 'Message',
      send: ' Send',
      yourFeedbackReceived: 'Your feedback received',
    },
    notifications: {
      notifications: 'Notifications',
    },
    transactions: {
      transactions: 'Transactions',
      details: 'Details',
      duration: 'Duration',
      power: 'Power',
      energy: 'Energy',
      address: 'Address',
      cardNumber: 'Card Number',
    },
    dropDownAlert: {
      error: 'Error',
      generalError: 'Error encountered',
      generalSuccess: 'Order completed successfully',
      fillCode: 'Please, enter charger code',
      fillAmount: 'Please, enter price amount',
      chargerNotExist: "this kind of charger don't exist",
      successOnFavoriteAdd: 'Successfully added charger',
      successOnFavoriteRemove: 'Charger deleted successfully',
      informationUpdatedSuccessfully: 'Information updated successfully',
      avatarUpdatedSuccessfully: 'Avatar updated successfully',
      thisUserIsBlocked: 'This user is blocked',
      areYouSureYouWantToLogOut: 'Are you sure you want to log out?',
      needInternetConnection: 'Need internet connection',
      registration: {
        fillPhoneNumber: 'Please, fill phone number',
        fillName: 'Please, fill name',
        fillSurname: 'Please, fill surname',
        incorrectEmail: 'Email is not valid',
        codeSentSuccessfully: 'Code sent successfully',
        codeLengthError: 'Sms code should be exactly 4 digits long',
        incorrectCode: 'code is incorrect',
        emailAlreadyToken: 'The email has already been taken',
        phoneAlreadyToken: 'The phone number has already been taken.',
        passwordNotEqual: 'Passwords not equal',
        needsCardAddOrPleaseSkip: 'Needs card add, or skip',
      },
      editFirstname: {
        firstNameNotEmpty: 'Please, Fill The First Name Field',
        minSize: 'First Name should be at least 3 characters long',
        firstNameChangeSuccess: 'First Name Changed Successfully!',
      },
      editLastname: {
        lastNameNotEmpty: 'Please, Fill The Last Name Field',
        minSize: 'Last Name should be at least 3 characters long',
        lastNameChangeSuccess: 'Last Name Changed Successfully!',
      },
      editEmail: {
        incorrectFormat: 'Email Format is Incorrect',
        editedSuccessfully: 'Email Edited Successfully',
      },
      editPhoneNumber: {
        success: 'Phone Number Edited Successfully',
        phoneTaken: 'Phone Number Already Taken',
      },
      editPassword: {
        success: 'Password Edited Successfully',
        fillCurrentPassword: 'Please, Fill Current Password Field',
        fillRepeatPassword: 'Please, Fill Repeat Password Filed',
        fillNewPassword: 'Please, Fill New Password Field',
        minSize: 'Password Field Should Contain At Least 8 Characters',
        passwordsMismatch: "Passwords aren't identical",
        passwordNotValid: 'Current Password Was Not Correct',
      },
      auth: {
        phoneNumberLength: 'The phone number should be exactly 9 digits long.',
        passwordNotEmpty: 'The password field should not be empty',
        userNotFound: 'User not found',
      },
      forgotPassword: {
        smsCodeLength: 'Sms code should be exactly 4 digits long',
        getVerificationCode: 'Get verification code',
        userNotFound: 'There is no such user with this phone number',
        smsCodeExpired: 'Sms code expired',
        fillCode: 'Please, fill the code',

        newPasswordNotFilled: 'Please, fill the New Password field',
        repeatNewPasswordNotFilled: 'Please fill the Repeat New Password field',
        newPasswordIncorrectLength:
          'New password should contain at least 8 symbols',
        passwordChangedSuccessfully: 'Password changed successfully',
        passwordsNotFilled: 'Please, fill  passwords fields',
        verificationCodeIsIncorrect: 'Verification code is incorrect',
      },
      charging: {
        areUSore: 'Are you sore you want to finish?',
        needToLogIn: 'You need to log in ',
        noRouteFound: 'No route found',
      },
      home: {
        noRouteFound: 'No route found',
      },
    },
    partners: {
      partnersOrganizations: 'Partner Organizations',
    },
    filterTypes: {
      free: 'Free',
      inUse: 'In use',
      fast: 'Fast',
      lvl2: 'Lvl2',
      public: 'Public',
      notPublic: 'Non Public',
    },
  },
}
