/* eslint-disable max-len */
import privacyPolicy from './privacyPolicyKa';

export default {
  translation: {
    hello: 'გამარჯობა',
    notFound: 'ვერ მოიძებნა',
    back: 'უკან',
    enter: 'შესვლა',
    next: 'შემდეგი',
    save: 'შენახვა',
    gel: 'ლარი',
    turnOn: 'ჩართვა',
    km: 'კმ',
    kwh: 'კვტ/სთ',
    kw: 'კვტ.',
    from: '-დან',
    till: '-მდე',
    yes: 'დიახ',
    no: 'არა',
    done: 'კარგი',
    minute: 'წთ',
    loading: 'იტვირთება ...',
    cancel: 'გაუქმება',
    update: 'შესწორება',
    pleaseFillInput: 'გთხოვთ შეავსოთ ველი',
    needLocation: 'საჭიროა წვდომა ლოკაციაზე',
    locationIsDenied: 'ლოკაციაზე წვდომა აკრძალულია',
    navigateToSettings: 'პარამეტრებში გადასვლა',
    chargerString: 'დამტენი',
    IAgree: 'ვეთანხმები',
    welcome: 'მოგესალმებით!',
    phoneCodes: 'ტელეფონის კოდები',
    authentication: {
      authentication: 'ავტორიზაცია',
      number: 'ნომერი',
      password: 'პაროლი',
      forgotPassword: 'დაგავიწყდათ პაროლი?',
      newRegistration: 'არ ხართ დარეგისტრირებული?',
      forgotPasswordPage: {
        recoverPassword: 'პაროლის აღდგენა',
        smsCode: 'SMS კოდი',
        receiveCode: 'კოდის მიღება',
        newPassword: 'ახალი პაროლი',
        repeatPassword: 'გაიმეორეთ პაროლი',
        codeValidity: 'კოდი ვალიდურია 3 წუთის განმავლობაში',
      },
      registration: {
        registration: 'რეგისტრაცია',
        name: 'სახელი',
        surname: 'გვარი',
        email: 'ელ-ფოსტა',
        password: 'პაროლი',
        repeatPassword: 'გაიმეორეთ პაროლი',
        skip: '  გამოტოვება',
        success: 'თქვენ წარმატებკით დარეგისტრირდით, შეგიძლიათ დამუხტოთ მანაქანა!',
      },
    },
    home: {
      allChargers: 'ყველა დამტენი',
      authorization: 'ავტორიზაცია',
      location: 'ლოკაცია',
      locationRequestTextOnDenied:
        'სიზუსტისთვის საჭიროა ჩართოთ ლოკაციის სერვისი',
      organization: 'ორგანიზაცია',
    },
    drawer: {
      tariff: 'ტარიფები',
      contact: 'კონტაქტი',
      faq: 'FAQ',
      partners: 'პარტნიორები',
      termsAndConditions: 'წესები და პირობები',
      settings: 'პარამეტრები',
      transactions: 'ტრანზაქციები',
      notifications: 'შეტყობინებები',
      logOut: 'გამოსვლა',
      changeAvatar: 'ავატარის შეცვლა',
    },
    settings: {
      settings: 'პარამეტრები',
      firstname: 'სახელი',
      lastname: 'გვარი',
      mail: 'ელ-ფოსტა',
      phone: 'ტელეფონი',
      cards: 'ბარათები',
      password: 'პაროლი',
      confirmed: 'დადასტურებულია',
      notconfirmed: 'არ არის დადასტურებული',
      notAdded: 'არ არის დამატებული',
      add: 'დამატება',
      editFirstname: 'სახელის შეცვლა',
      newFirstname: 'ახალი სახელი',
      editLastname: 'გვარის შეცვლა',
      newLastname: 'ახალი გვარი',
      editPhoneNumber: 'ნომრის შეცვლა',
      phoneNumber: 'ნომერი',
      editPassword: 'პაროლის შეცვლა',
      currentPassword: 'არსებული პაროლი',
      newPassword: 'ახალი პაროლი',
      repeatPassword: 'გაიმეორეთ პაროლი',
      editCard: 'გადახდის მეთოდი',
      addCard: 'დაამატე ბარათი',
      editMail: 'ელ-ფოსტის შეცვლა',
      newMail: 'ახალი ელ-ფოსტა',
      mapColor: 'რუკის ფერი',
      automatic: 'ავტომატური',
      mapColorLight: 'ნათელი',
      mapColorDark: 'ბნელი',
      chooseMapMode: 'აირჩეთ რუკის რეჟიმი',
      addCar: 'მანქანის დამატება',
      manufacturer: 'მწარმოებელი',
      model: 'მოდელი',
    },
    popup: {
      legend: 'ლეგენდა',
      fastNonCommercial: 'სწრაფი არასაჯარო',
      fastCommercial: 'სწრაფი საჯარო',
      lvl2NonCommercial: 'მე-2-ე დონის არასაჯარო',
      lvl2Commercial: 'მე-2-ე დონის საჯარო',
      busy: 'დაკავებული',
      notWorking: 'არ მუშაობს',
      free: 'თავისუფალი',
      thankYou: 'მადლობა',
      automobileChargingFinished: 'ავტომობილის დამუხტვა დასრულებულია',
      chargingFinishedWarning: 'თუ 20 წუთის განმავლობაში არ გამოერთებთ კაბელს, მოგიწევთ ჯარიმის გადახდა ყოველ დამატებით წუთზე',
      chargeOff: 'ჩამოგეჭრათ',
      returned: 'დაგიბრუნდათ',
      continueCharging: 'დამუხტვის გაგრძელება',
      finishedChargingOfAutomobile: 'დამუხტვის პროცესი დასრულებულია',
      warningTextBeforeFine: 'თუ ამ დროის განმავლობაში არ გამოერთებთ კაბელს, მოგიწევთ ჯარიმის გადახდა ყოველ დამატებით წუთზე',
      yourChargingOnFineStarted: 'თქვენი ჯარიმის ათვლა დაიწყო',
      bankrupt: 'არასაკმარისი თანხა',
      paymentFailed: 'ბარათით გადახდა ვერ განხორციელდა.',
      processFailed: 'პროცესი წარუმატებლად დასრულდა',
    },
    charger: {
      chargeWitchCode: 'დამუხტვა კოდით',
      enterCode: 'ჩაწერეთ კოდი',
      turnOn: 'ჩართვა',
      allChargerList: 'დამტენების სრული სია',
      lastUsed: 'ბოლოს გამოყენებული',
    },
    chargerDetail: {
      seeOnMap: 'რუკაზე ნახვა',
      currentPrices: 'მიმდინარე ტარიფები',
      kw: 'კილოვატები',
      tariffs: 'ტარიფები',
      speedRange: 'სიჩქარის ზღვრები',
      minutesPrice: '15 წუთის ღირებულება',
      connectors: 'შესაერთებელი',
      additionalServices: 'დამატებითი სერვისები',
      powerOfChargerType: 'სიმძლავრე {{power}}კვტ/სთ',
      code: 'კოდი:#{{code}}',
      pleaseAddCardFirst: 'საჭიროა ბარათის დამატება',
      maxAllowedCarCharing: 'შესაძლებელია მაქსიმუმ 2 ავტომობილის დამუხტვა',
      selectConnector: 'გთხოვთ აირჩიოთ შესაერთებელი',
      chargerIsBusy: 'დამტენი დაკავებულია',
      minutes: 'წუთები',
    },
    notAuthorized: {
      notAuthorizedText: 'დამუხტვის დასაწყებად, გაიარეთ ავტორიზაცია',
    },
    chooseChargeMethod: {
      choose: 'აირჩიეთ',
      chooseChargeMethod: 'აირჩიეთ დამუხტვის სასურველი მეთოდი',
      or: 'ან',
      untilTurnOff: 'სრულად დამუხტვამდე',
      withEnteringPrice: 'თანხის მითითებით',
    },
    charging: {
      charge: 'დამუხტვა',
      chargeAnotherCar: 'სხვა ავტომობილის დამუხტვა',
      finish: 'დასრულება',
    },
    chooseCard: {
      chooseCard: 'ბარათის არჩევა',
      enterPrice: 'გთხოვთ მიუთითეთ თანხის ოდენობა',
      chargingUntilPlugOff: 'სრულად დამუხტვამდე',
    },
    favourites: {
      favourites: 'ფავორიტები',
    },
    faq: {
      faq: 'ხდკ',
      frequentlyAskedQuestions: 'ხშირად დასმული კითხვები',
    },
    tariffs: {
      tariffs: 'ტარიფები',
      company: 'კომპანია',
      power: 'სიმძლავრე',
      chargerType: 'დამტენის ტიპი',
    },
    contact: {
      contact: 'კონტაქტი',
      address: 'მისამართი',
      phone: 'ტელეფონი',
      eMail: 'მეილი',
      facebookPage: 'ფეისბუქის გვერდი',
      webPage: 'ვებ-გვერდი',
      message: 'შეტყობინება',
      send: 'გაგზავნა',
      yourFeedbackReceived: 'თქვენი შეტყობინება მიღებულია',
    },
    notifications: {
      notifications: 'შეტყობინებები',
    },
    transactions: {
      transactions: 'ტრანზაქციები',
      details: 'დეტალები',
      duration: 'ხანგრძლივობა',
      power: 'სიმძლავრე',
      energy: 'ენერგია',
      address: 'მისამართი',
      cardNumber: 'ბარათის ნომერი',
      penaltyFee: 'ჯარიმა',
    },
    dropDownAlert: {
      error: 'შეცდომა',
      generalError: 'დაფიქსირდა შეცდომა',
      generalSuccess: 'მოთხოვნა წარმატებით დამუშავდა',
      pleaseAllowLocation: 'მარშრუტის სანახავად საჭიროა ლოკაციის ჩართვა',
      fillCode: 'გთხოვთ ჩაწეროთ დამტენის კოდი',
      fillAmount: 'გთხოვთ ჩაწეროთ თანხის ოდენობა',
      chargerNotExist: 'ასეთი  კოდით დამტენი არ მოიძებნა',
      successOnFavoriteAdd: 'დამტენი წარმატებით დაემატა',
      successOnFavoriteRemove: 'დამტენი წარმატებით წაიშალა',
      informationUpdatedSuccessfully: 'ინფორმაცია წარმატებით განახლდა',
      avatarUpdatedSuccessfully: 'ავატარი განახლებულია',
      thisUserIsBlocked: 'მომხმარებელი არ არის აქტიური',
      areYouSureYouWantToLogOut: 'დარწმუნებული ხართ რომ გსურთ გამოსვლა?',
      needInternetConnection: 'საჭიროა ინტერნეტთნ კავშირი',
      connectionProblem: 'დამტენთან კავშირის პრობლემაა, გთხოვთ დაელოდოთ',
      pleaseSeeIfChargerIsConnected:
        'გთხოვთ დარწმუნდეთ, რომ კაბელი სწორად არის შეერთებული',
      registration: {
        fillPhoneNumber: 'გთხოვთ ჩაწეროთ ტელეფონის ნომერი',
        fillName: 'გთხოვთ ჩაწეროთ სახელი სწორი ფორმატით',
        fillSurname: 'გთხოვთ ჩაწეროთ გვარი სწორი ფორმატით',
        incorrectEmail: 'იმეილის ფორმატი არ არის სწორი',
        codeSentSuccessfully: 'კოდი  წარმატებით გამოიგზავნა',
        codeLengthError: 'sms კოდი 4 ციფრისგან უნდა შედგებოდეს',
        incorrectCode: 'კოდი არ არის სწორი',
        emailAlreadyToken: 'ეს იმეილი ბაზაში უკვე არსებობს',
        phoneAlreadyToken: 'ეს ნომერი ბაზაში უკვე არსებობს',
        passwordNotEqual: 'პაროლები ერთმანეთს არ ემთხვევა',
        minPasswordTextLength: 'პაროლი უნდა შეიცავდეს მინ. 8 სიმბოლოს',
        needsCardAddOrPleaseSkip: 'საჭიროა ბარათის დამატება, ან გამოტოვეთ',
        pleaseSelectTermsAndConditions: 'გთხოვთ დაეთანხმოთ წესებს და პირობებს',
        alreadyExists: 'მომხმარებელი ასეთი ნომერით უკვე დარეგისტრირებულია!',
      },
      editFirstname: {
        firstNameNotEmpty: 'გთხოვთ ჩაწეროთ სახელი სწორი ფორმატით',
        minSize: ' ველი მინიმუმ 3 სიმბოლოს უნდა შეიცავდეს',
        firstNameChangeSuccess: 'სახელი წარმატებით შეიცვალა!',
      },
      editLastname: {
        lastNameNotEmpty: 'გთხოვთ ჩაწეროთ გვარი სწორი ფორმატით',
        minSize: 'ველი მინიმუმ 3 სიმბოლოს უნდა შეიცავდეს',
        lastNameChangeSuccess: 'გვარი წარმატებით შეიცვალა!',
      },
      editEmail: {
        incorrectFormat: 'ელ.ფოსტის ფორმატი არასწორია',
        editedSuccessfully: 'ელ.ფოსტა წარმატებით შეიცვალა!',
      },
      editPhoneNumber: {
        success: 'ტელეფონის ნომერი წარმატებით შეიცვალა!',
        phoneTaken: 'ეს ნომერი ბაზაში უკვე არსებობს',
      },
      editPassword: {
        success: 'პაროლი წარმატებით შეიცვალა',
        fillCurrentPassword: 'გთხოვთ, შეიყვანეთ მიმდინარე პაროლი',
        fillRepeatPassword: 'გთხოვთ, გაიმეოროთ პაროლი',
        fillNewPassword: 'გთხოვთ, შეიყვანოთ ახალი პაროლი',
        minSize: 'პაროლის ველი უნდა შეიცავდეს მინიმუმ 8 სიმბოლოს',
        passwordsMismatch: 'პაროლები არ ემთხვევა ერთმანეთს',
        passwordNotValid: 'თქვენს მიერ შეყვანილი მიმდინარე პაროლი არასწორია',
      },
      auth: {
        phoneNumberLength: 'მობილურის ნომერი უნდა შეიცავდეს 9 ციფრს',
        passwordNotEmpty: 'შეავსეთ პაროლის ველი',
        userNotFound: 'მობილურის ნომერი ან პაროლი არასწორია',
      },
      forgotPassword: {
        smsCodeLength: 'sms კოდი 4 ციფრისგან უნდა შედგებოდეს',
        getVerificationCode: 'ვერიფიკაციის კოდის მიღება',
        userNotFound: 'ამ ნომრით მომხმარებელი ვერ მოიძებნა',
        smsCodeExpired: 'sms კოდს ვადა გაუვიდა',
        fillCode: 'შეიყვანეთ sms კოდი',
        newPasswordNotFilled: 'გთხოვთ, შეიყვანოთ ახალი პაროლი',
        repeatNewPasswordNotFilled: 'გთხოვთ, გაიმეორეთ პაროლი',
        newPasswordIncorrectLength: 'პაროლი უნდა შეიცავდეს მინიმუმ 8 სიმბოლოს',
        passwordChangedSuccessfully: 'პაროლი წარმატებით შეიცვალა',
        passwordsNotFilled: 'გთხოვთ, შეავსოთ პაროლის ველები',
        verificationCodeIsIncorrect: 'ვერიფიკაციის კოდი არასწორია',
        doesNotExist: 'ასეთი ნომრით მომხმარებელი არ არსებობს!',
      },
      contact: {
        Address: 'დაფიქსირდა შეცდომა რუკის გახსნისას...',
        Facebook: 'დაფიქსირდა შეცდომა facebook-ის გახსნისას...',
        Mail: 'დაფიქსირდა შეცდომა მეილის გახსნისას...',
        Phone: 'დაფიქსირდა შეცდომა ზარის განხორციელებისას...',
        Web: 'დაფიქსირდა შეცდომა ვებგვერდის გახსნისას...',
      },
      charging: {
        areUSore: 'დარწმუნებული ხართ, რომ გინდათ დასრულება?',
        needToLogIn: 'გაიარეთ ავტორიზაცია',
        noRouteFound: 'მარშრუტი ვერ მოიძებნა',
      },
      home: {
        noRouteFound: 'მარშრუტი ვერ მოიძებნა',
      },
      addCar: {
        firstManufacturer: 'გთხოვთ, პირველ რიგში მწარმოებელი აირჩიოთ...',
        uSureToDelete: 'ნამდვილად გსურთ ავტომობილის წაშლა?',
        youCanAddCar: 'ამჟამათ თქვენ ავტომობილი დამატებული არ გაქვთ, გსურთ დაამატოთ?',
      },
    },
    addCar: {
      addedCars: 'დამატებული ავტომობილები',
      youHaveNoCars: 'თქვენ ჯერ არ გაქვთ დამატებული ავტომობილი...',
    },
    creditCards: {
      uSureToDelete: 'დარწმუნებული ხართ, რომ ბარათის წაშლა გსურთ?',
    },
    partners: {
      partnerOrganizations: 'პარტნიორი ორგანიზაციები',
    },
    filterTypes: {
      free: 'თავისუფალი',
      inUse: 'დაკავებული',
      fast: 'სწრაფი',
      lvl2: 'მე-2-ე დონის',
      public: 'საჯარო',
      notPublic: 'არასაჯარო',
    },
    privacyPolicy,
  },
};
