export default {
  translation: {
    hello: 'გამარჯობა',
    notFound: 'ვერ მოიძებნა',
    back: 'უკან',
    enter: 'შესვლა',
    next: 'შემდეგი',
    save: 'შენახვა',
    gel: 'ლარი',
    turnOn: 'ჩართვა',
    km: 'კმ',
    kwh: 'კვ/სთ',
    from: '-დან',
    till: '-მდე',
    yes: 'დიახ',
    no: 'არა',
    loading: 'იტვირთება ...',
    authentication: {
      authentication: 'ავტორიზაცია',
      number: 'ნომერი',
      password: 'პაროლი',
      forgotPassword: 'დაგავიწყდა პაროლი?',
      newRegistration: 'არ ხართ დარეგისტრირებული?',
      forgotPasswordPage: {
        recoverPassword: 'პაროლის აღდგენა',
        smsCode: 'Sms კოდი',
        receiveCode: 'კოდის მიღება',
        newPassword: 'ახალი პაროლი',
        repeatPassword: 'გაიმეორეთ პაროლი',
        codeValidity: 'კოდი ვალიდურია 3 წუთის განმავლობაში',
      },
      registration: {
        registration: 'რეგისტრაცია',
        name: 'სახელი',
        surname: 'გვარი',
        email: 'ელ-ფოსტა',
        password: 'პაროლი',
        repeatPassword: 'გაიმეორეთ პაროლი',
        skip: '  გამოტოვება',
      },
    },
    home: {
      allChargers: 'ყველა დამტენი',
      authorization: 'ავტორიზაცია',
      location: 'ლოკაცია',
      organization: 'ორგანიზაცია',
    },
    drawer: {
      tariff: 'ტარიფები',
      contact: 'კონტაქტი',
      faq: 'ხდკ',
      partners: 'პარტნიორები',
      terms_and_conditions: 'წესები და პირობები',
      settings: 'პარამეტრები',
      transactions: 'ტრანზაქციები',
      notifications: 'შეტყობინებები',
      logOut: 'გამოსვლა',
    },
    settings: {
      settings: 'პარამეტრები',
      firstname: 'სახელი',
      lastname: 'გვარი',
      mail: 'ელ-ფოსტა',
      phone: 'ტელეფონი',
      cards: 'ბარათები',
      password: 'პაროლი',

      confirmed: 'დადასტურებული',
      notconfirmed: 'არ არის დადასტურებული',
      notAdded: 'არ არის დამატებული',

      editFirstname: 'სახელის შეცვლა',
      newFirstname: 'ახალი სახელი',

      editLastname: 'გვარის შეცვლა',
      newLastname: 'ახალი გვარი',

      editPhoneNumber: 'ნომრის შეცვლა',
      phoneNumber: 'ნომერი',
      editPassword: 'პაროლის შეცვლა',
      currentPassword: 'ახლანდელი პაროლი',
      newPassword: 'ახალი პაროლი',
      repetePassword: 'გაიმეორეთ პაროლი',

      editCard: 'გადახდის მეთოდი',
      addCard: 'დაამატე ბარათი',
      editMail: 'ელ-ფოსტის შეცვლა',
      newMail: 'ახალი ელ-ფოსტა',
    },
    popup: {
      legend: 'ლეგენდა',
      fastNonCommercial: 'სწრაფი არასაჯარო',
      fastCommercial: 'სწრაფი საჯარო',
      lvl2NonCommercial: 'ლვლ 2 არასაჯარო',
      lvl2Commercial: 'ლვლ 2 საჯარო',
      busy: 'დაკავებული',
      notWorking: 'არ მუშაობს',
      free: 'თავისუფალი',
      thankYou: 'მადლობა',
      automobileChargingFinished: 'ავტომობილის დატენვა დასრულენულია',
      chargingFinishedWarning:
        'თუ 20 წუთის განმავლობაში არ გამოერთებთ კაბელს მოგიწევთ, ჯარიმის გადახდა ყოველ დამატებით წუთზე',
      chargeOff: 'ანგარიშიდან ჩამოგეჭრათ',
      returned: 'დაგიბრუნდათ',
      continueCharging: 'დატენვის გაგრძელება',
      finishedChargingOfAutomobile: 'თქვენი ავტომობილის დატევა დასრულდა',
    },
    charger: {
      chargeWitchCode: 'დატენვა კოდით',
      enterCode: 'ჩაწერეთ კოდი',
      turnOn: 'ჩართვა',
      allChargerList: 'დამტენების სრული სია',
      lastUsed: 'ბოლოს გამოყენებული',
    },
    chargerDetail: {
      seeOnMap: 'რუკაზე ნახვა',
      currentPrices: 'მიმდინარე ტარიფები',
      connectors: 'ქონექტორები',
      additionalServices: 'დამატებითი სერვისები',
      powerOfChargerType: 'სიმძლავრე {{power}}კვ/სთ',
    },
    notAuthorized: {
      notAuthorizedText:
        'იმისთვის, რომ შეძლოთ ავტომობილის დატენვა საჭიროა გაიაროთ ავტორიზაცია',
    },
    chooseChargeMethod: {
      choose: 'აირჩიეთ',
      chooseChargeMethod: 'აირჩიეთ თქვენთვის სასურველი დატენვის მეთოდი',
      or: 'ან',
      untilTurnOff: 'გათიშვამდე',
      withEnteringPrice: 'თანხის მითითებით',
    },
    charging: {
      charge: 'დატენვა',
      chargeAnotherCar: 'დატენე სხვა ავტომობილი',
      finish: 'დასრულება',
    },
    chooseCard: {
      chooseCard: 'ბარათის არჩევა',
      enterPrice: 'მიუთითეთ თანხა',
    },
    favourites: {
      favourites: 'ფავორიტები',
    },
    faq: {
      faq: 'ხდკ',
      frequentlyAskedQuestions: 'ხშირად დასმული კითხვები',
    },
    tariffs: {
      tariffs: 'ტარიფები',
      company: 'კომპანია',
      power: 'სიმძლავრე',
      chargerType: 'დამტენის ტიპი',
    },
    contact: {
      contact: 'კონტაქტი',
      address: 'მისამართი',
      phone: 'ტელეფონი',
      eMail: 'მეილი',
      facebookPage: 'ფეისბუქის გვერდი',
      webPage: 'ვებ-გვერდი',
      message: 'შეტყობინება',
    },
    notifications: {
      notifications: 'შეტყობინებები',
    },
    transactions: {
      transactions: 'ტრანზაქციები',
      details: 'დეტალები',
      duration: 'ხანგრძლივობა',
      power: 'სიმძლავრე',
      energy: 'ენერგია',
      address: 'მისამართი',
      cardNumber: 'ბარათის ნომერი',
    },
    dropDownAlert: {
      generalError: 'დაფიქსირდა შეცდომა',
      fillCode: 'გთხოვთ ჩაწროთ დამტენის კოდი',
      chargerNotExist: 'ასეთი დამტენის კოდი არ არსებობს',
      registration: {
        fillPhoneNumber: 'გთხოვთ ჩაწროთ ტელეფონის ნომერი',
        fillName: 'გთხოვთ ჩაწროთ სახელი',
        fillSurname: 'გთხოვთ ჩაწროთ გვარი',
        incorrectEmail: 'ემაილი არა არის სწორი',
        codeSentSuccessfully: 'კოდი გამოიგზავნა წარმატებით',
        codeLengthError: 'sms კოდი 4 ციფრისგან უნდა შედგებოდეს',
        incorrectCode: 'კოდი არ არის სწორი',
        emailAlreadyToken: 'ეს ემაილი ბაზაში უკვე არსებობს',
        phoneAlreadyToken: 'ეს ნომერი ბაზაში უკვე არსებობს',
        passwordNotEqual: 'პაროლები ერთმანეთს არ ემთხვევა',
        minPasswordTextLength: 'მინიმუმ 8 სიმბოლო უნდა იყოს პაროლში',
      },
      editFirstname: {
        firstNameNotEmpty: 'გთხოვთ, შეავსეთ სახელის ველი',
        minSize: 'სახელის ველი მინიმუმ 3 სიმბოლოს უნდა შეიცავდეს',
        firstNameChangeSucess: 'სახელი წარმატებით შეიცვალა!',
      },
      editLastname: {
        lastNameNotEmpty: 'გთხოვთ, შეავსეთ გვარის ველი',
        minSize: 'გვარის ველი მინიმუმ 3 სიმბოლოს უნდა შეიცავდეს',
        lastNameChangeSucess: 'გვარი წარმატებით შეიცვალა!',
      },
      editEmail: {
        incorrectFormat: 'ელ.ფოსტის ფორმატი არასწორია',
        editedSuccssesfully: 'ელ.ფოსტა წარმატებით შეიცვალა!',
      },
      editPhoneNumber: {
        success: 'ტელეფონის ნომერი წარმატებით შეიცვალა!',
        phoneTaken: 'ეს ტელეფონის ნომერი დაკავებულია',
      },
      editPassword: {
        success: 'პაროლი წარმატებით შეიცვალა',
        fillCurrentPassword: 'გთხოვთ, შეიყვანეთ ამჟამინდელი პაროლი',
        fillRepetePassword: 'გთხოვთ, გაიმეოროთ პაროლი',
        fillNewPassword: 'გთხოვთ, შეიყვანოთ ახალი პაროლი',
        minSize: 'პაროლის ველი მინიმუმ 8 სიმბოლოს უნდა შეიცავდეს',
        passwordsMismatch: 'პაროლები არ ემთხვევა ერთმანეთს',
        passwordNotValid: 'თქვენს მიერ შეყვანილი ამჟამინდელი პაროლი არასწორია',
      },
      auth: {
        phoneNumberLength: 'მობილურის ნომერი 9 ციფრს უნდა შეიცავდეს',
        passworNotEmpty: 'პაროლის ველი ცარიელი არ უნდა იყოს',
        userNotFound: 'მომხმარებელი ვერ მოიძებნა ბაზაში',
      },
      forgotPassword: {
        smsCodeLength: 'sms კოდი 4 ციფრისგან უნდა შედგებოდეს',
        getVerificationCode: 'მიიღეთ ვერიფიკაციის კოდი',
        userNotFound: 'ამ ნომრით მომხმარებელი ვერ მოიძებნა',
        smsCodeExpired: 'sms კოდს ვადა გაუვიდა',
        fillCode: 'შეიყვანეთ sms კოდი',
        newPasswordNotFilled: 'გთხოვთ, შეიყვანოთ ახალი პაროლის ველი',
        repeteNewPasswordNotFilled: 'გთხოვთ, გაიმეორეთ პაროლი',
        newPasswordIncorrectLength: 'პაროლი მინიმუმ 8 სიმბოლოს უნდა შეიცავდეს',
        passwordChangedSuccessfully: 'პაროლი წარმატებით შეიცვალა',
      },
      charging: {
        areUSore: 'დარწმუნებული ხართ რომ გინდათ დასრულება',
      },
      home: {
        noRouteFound: 'გზა ვერ მოიძებნა',
      },
    },
    partners: {
      partnerOrganizations: 'პარტნიორი ორგანიზაციები',
    },
    filterTypes: {
      free: 'თავისუფალი',
      inUse: 'დაკავებული',
      fast: 'სწრაფი',
      lvl2: 'ლვლ2',
      public: 'საჯარო',
      notPublic: 'არასაჯარო',
    },
  },
}
