export default {
  alertCircle: require('./icons/alert-circle.png'),
  iosBack: require('./icons/ios_back.png'),
  arrowLeft: require('./icons/arrow_left.png'),
  arrowRight: require('./icons/arrow_right.png'),
  arrowUp: require('./icons/arrow-up.png'),
  user: require('./icons/user.png'),
  greenTick: require('./icons/green-tick.png'),
  blueUser: require('./icons/blue-user.png'),
  mail: require('./icons/mail.png'),
  transaction: require('./icons/transaction.png'),
  mapPin: require('./icons/ic_map_pin.png'),
  mapPin2: require('./icons/map-pin.png'),
  orangeTrash: require('./icons/orange-trash.png'),
  lock: require('./icons/lock.png'),
  alertCircle2: require('./icons/ic_alert-circle.png'),
  charge: require('./icons/ic_charge.png'),
  checkCircle: require('./icons/check-circle.png'),
  briefCase: require('./icons/briefcase.png'),
  chevronUp: require('./icons/chevron-up.png'),
  greenCheckmark: require('./icons/green_checkmark.png'),
  circle: require('./icons/cicle.png'),
  greenUser: require('./icons/green-user.png'),
  bluePencil: require('./icons/blue-pencil.png'),
  creditCard: require('./icons/credit-card.png'),
  close: require('./icons/close.png'),
  filterType: require('./icons/ic_filterType.png'),
  back: require('./icons/Back.png'),
  zap: require('./icons/zap.png'),
  cornerUpLeft: require('./icons/corner-up-left.png'),
  cornerUpRight: require('./icons/corner-up-right.png'),
  phone: require('./icons/phone.png'),
  chervonRight: require('./icons/chevron-right.png'),
  delete: require('./icons/Delete.png'),
  frame: require('./icons/Frame.png'),
  favorite: require('./icons/ic_favorite.png'),
  iconSearch: require('./icons/icon-search.png'),
  chargerWithGradient: require('./icons/charger_with_gradient.png'),
  menu: require('./icons/ic_menu.png'),
}

export const Partners = {
  socar: require('./icons/partners/socar.png'),
  neogas: require('./icons/partners/neogas.png'),
  gulf: require('./icons/partners/gulf.png'),
  m2: require('./icons/partners/m2.png'),
  wissol: require('./icons/partners/wissol.png'),
  bog: require('./icons/partners/bog.png'),
}
